//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ProjectMsg
{
    [Serializable]
    public class HandCmdMsg : Message
    {
        public const string k_RosMessageName = "project_msg/HandCmd";
        public override string RosMessageName => k_RosMessageName;

        public string data;

        public HandCmdMsg()
        {
            this.data = "";
        }

        public HandCmdMsg(string data)
        {
            this.data = data;
        }

        public static HandCmdMsg Deserialize(MessageDeserializer deserializer) => new HandCmdMsg(deserializer);

        private HandCmdMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.data);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "HandCmdMsg: " +
            "\ndata: " + data.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
